// Shared carrier and product type data for quotes and policies

export const PRODUCT_TYPES = [
  { id: 'aca', name: 'Health Insurance (ACA)' },
  { id: 'annuities', name: 'Annuities' },
  { id: 'dental', name: 'Dental' },
  { id: 'final_expense', name: 'Final Expense' },
  { id: 'life', name: 'Life Insurance' },
  { id: 'medicaid', name: 'Medicaid' },
  { id: 'medicare', name: 'Medicare' },
  { id: 'private', name: 'Private' },
  { id: 'supplemental', name: 'Supplemental' },
  { id: 'travel', name: 'Travel' },
  { id: 'vision', name: 'Vision' },
];

export const CARRIERS_BY_TYPE: Record<string, string[]> = {
  aca: [
    'Ambetter',
    'Blue Cross Blue Shield',
    'Bright Health',
    'Cigna',
    'Friday Health Plans',
    'Humana',
    'Kaiser Permanente',
    'Molina Healthcare',
    'Oscar Health',
    'UnitedHealthcare',
  ].sort(),
  annuities: [
    'Allianz',
    'American Equity',
    'Athene',
    'Jackson National',
    'Lincoln Financial',
    'MassMutual',
    'Nationwide',
    'Pacific Life',
    'Prudential',
    'Transamerica',
  ].sort(),
  dental: [
    'Aetna',
    'Cigna',
    'Delta Dental',
    'Guardian',
    'Humana',
    'MetLife',
    'Renaissance Dental',
    'United Concordia',
    'UnitedHealthcare',
  ].sort(),
  final_expense: [
    'American Amicable',
    'Foresters Financial',
    'Globe Life',
    'Mutual of Omaha',
    'Royal Neighbors of America',
    'Transamerica',
  ].sort(),
  life: [
    'AIG',
    'Allstate',
    'American General',
    'Banner Life',
    'Brighthouse Financial',
    'John Hancock',
    'Lincoln Financial',
    'MassMutual',
    'MetLife',
    'Mutual of Omaha',
    'New York Life',
    'Northwestern Mutual',
    'Pacific Life',
    'Principal',
    'Protective',
    'Prudential',
    'State Farm',
    'Transamerica',
  ].sort(),
  medicaid: [
    'Aetna Better Health',
    'AmeriHealth Caritas',
    'Molina Healthcare',
    'UnitedHealthcare Community Plan',
  ].sort(),
  medicare: [
    'Aetna',
    'Anthem',
    'BCBS',
    'Centene',
    'CIGNA',
    'Clover Health',
    'Devoted Health',
    'Elevance Health',
    'Friday Health Plans',
    'Healthfirst',
    'HealthPartners',
    'Highmark',
    'Humana',
    'Independence Blue Cross',
    'Kaiser Permanente',
    'L.A. Care Health Plan',
    'Medica',
    'Molina Healthcare',
    'Mutual of Omaha',
    'Oscar Health',
    'Premera Blue Cross',
    'Priority Health',
    'SCAN Health Plan',
    'SelectHealth',
    'United American',
    'UnitedHealthcare',
    'Wellcare',
    'WellCare Health Plans',
    'Aetna Medicare',
    'Blue Cross Medicare Advantage',
    'CIGNA Medicare',
    'Devoted Health Medicare',
    'Elevance Medicare',
    'Friday Health Medicare',
    'Healthfirst Medicare',
    'HealthPartners Medicare',
    'Highmark Medicare',
    'Humana Medicare',
    'Independence Medicare',
    'Kaiser Medicare',
    'L.A. Care Medicare',
    'Medica Medicare',
    'Molina Medicare',
    'Mutual of Omaha Medicare',
    'Oscar Medicare',
    'Premera Medicare',
    'Priority Medicare',
    'SCAN Medicare',
    'SelectHealth Medicare',
    'United American Medicare',
    'UnitedHealthcare Medicare',
    'Wellcare Medicare',
    'WellCare Medicare Plans',
  ].sort(),
  private: [
    'Aetna',
    'Blue Cross Blue Shield',
    'Cigna',
    'Humana',
    'UnitedHealthcare',
  ].sort(),
  supplemental: [
    'Aflac',
    'Allstate',
    'Colonial Life',
    'Combined Insurance',
    'Gerber Life',
    'MetLife',
    'Mutual of Omaha',
    'UnitedHealthcare',
  ].sort(),
  travel: [
    'Allianz Global Assistance',
    'AXA Assistance USA',
    'Berkshire Hathaway Travel Protection',
    'IMG Global',
    'InsureMyTrip',
    'Seven Corners',
    'Travelex Insurance',
    'Travel Guard',
  ].sort(),
  vision: [
    'EyeMed',
    'Humana',
    'MetLife',
    'UnitedHealthcare',
    'VSP Vision Care',
  ].sort(),
};

export function getCarriersByProductType(productType: string): string[] {
  return CARRIERS_BY_TYPE[productType] || [];
}
